"""
Genre inference for Marco's New Release archive.
Built from musical-domain knowledge of each artist's stylistic home.

Taxonomy (primary buckets, coherent with the curation):
  soulful-house   : soulful/deep/afro house, garage, broken-beat club
  broken-beat     : bruk, future-jazz/club, UK leftfield soul-jazz
  uk-jazz         : contemporary London jazz scene
  jazz            : modern/spiritual/straight-ahead/fusion jazz
  neo-soul        : neo-soul, contemporary R&B, future-soul
  soul-funk       : classic/modern soul, funk, disco
  hip-hop         : rap, boom-bap, trap, conscious
  electronic      : techno, IDM, ambient, downtempo, bass, leftfield
  world           : afrobeat, afro, latin, indian, global fusion
  alt             : alt/indie/rock/art-pop/singer-songwriter
  classical       : modern classical, soundtrack, orchestral
Each artist may carry 1-3 genres; the first is the primary.
"""

GENRES = {
    # ---- soulful house / dance core ----
    "Louie Vega": ["soulful-house", "soul-funk"],
    "Kenny Dope": ["soulful-house", "hip-hop"],
    "Masters At Work": ["soulful-house"],
    "Riva Starr": ["soulful-house", "electronic"],
    "Charles Webster": ["soulful-house", "electronic"],
    "Miguel Migs": ["soulful-house"],
    "Atjazz": ["soulful-house", "broken-beat"],
    "Honey Dijon": ["soulful-house"],
    "DJ Minx": ["soulful-house"],
    "Moodymann": ["soulful-house", "soul-funk"],
    "Amp Fiddler": ["soul-funk", "soulful-house"],
    "Dames Brown": ["soulful-house", "soul-funk"],
    "Crazy P": ["soulful-house", "soul-funk"],
    "The Blessed Madonna": ["soulful-house", "electronic"],
    "Austin Ato": ["soulful-house"],
    "Get Physical Radio": ["soulful-house", "electronic"],
    "Groove Armada": ["electronic", "soulful-house"],
    "Deep Dish": ["soulful-house", "electronic"],
    "Atmos Blaq": ["soulful-house"],
    "Sio": ["soulful-house"],
    "beatsbyhand": ["soulful-house"],
    "MÖRDA": ["soulful-house"],
    "Pellegrino": ["soulful-house", "world"],
    "Nu Genea": ["world", "soulful-house"],
    "Willy Soul": ["soulful-house"],
    "Funki Cadets": ["broken-beat", "soulful-house"],
    "DJ HANSEN": ["soulful-house"],
    "Butch": ["electronic", "soulful-house"],
    "Romare": ["electronic", "soulful-house"],
    "soho": ["soulful-house"],
    "Mike Sb": ["soulful-house"],
    "Lady Skatina": ["soulful-house"],
    "Spray": ["soulful-house"],

    # ---- broken-beat / bruk / club-jazz ----
    "Henry Wu": ["broken-beat", "uk-jazz"],
    "Kamaal Williams": ["broken-beat", "uk-jazz"],
    "IG Culture": ["broken-beat"],
    "Blue Lab Beats": ["broken-beat", "uk-jazz"],
    "Koralle": ["broken-beat", "electronic"],
    "Demae": ["broken-beat", "neo-soul"],
    "Marla Kether": ["broken-beat", "uk-jazz"],
    "Shy One": ["broken-beat"],
    "Yarni": ["broken-beat", "electronic"],
    "Kaidi Akinnibi": ["uk-jazz", "broken-beat"],

    # ---- UK jazz scene ----
    "Shabaka": ["uk-jazz", "jazz"],
    "Nubya Garcia": ["uk-jazz", "jazz"],
    "Ezra Collective": ["uk-jazz"],
    "Kokoroko": ["uk-jazz", "world"],
    "Nubiyan Twist": ["uk-jazz", "world"],
    "GoGo Penguin": ["uk-jazz", "jazz"],
    "Alfa Mist": ["uk-jazz", "neo-soul"],
    "Joe Armon-Jones": ["uk-jazz", "broken-beat"],
    "Yussef Dayes": ["uk-jazz", "jazz"],
    "Femi Koleoso": ["uk-jazz"],
    "Oscar Jerome": ["uk-jazz", "neo-soul"],
    "Run Logan Run": ["uk-jazz"],
    "Chiminyo": ["uk-jazz", "electronic"],
    "Charlie Stacey": ["uk-jazz"],
    "Quinn Oulton": ["uk-jazz", "neo-soul"],
    "Alabaster DePlume": ["uk-jazz", "jazz"],
    "Kae Tempest": ["uk-jazz", "hip-hop"],

    # ---- jazz (broad / spiritual / fusion / straight-ahead) ----
    "Terrace Martin": ["jazz", "neo-soul"],
    "Robert Glasper": ["jazz", "neo-soul"],
    "Kamasi Washington": ["jazz"],
    "Esperanza Spalding": ["jazz"],
    "Chet Baker": ["jazz"],
    "Miles Davis": ["jazz"],
    "Duke Ellington": ["jazz"],
    "Nina Simone": ["jazz", "soul-funk"],
    "Dianne Reeves": ["jazz"],
    "Pat Metheny": ["jazz"],
    "John Scofield": ["jazz"],
    "Bill Frisell": ["jazz"],
    "Chris Potter": ["jazz"],
    "John Patitucci": ["jazz"],
    "Stanley Clarke": ["jazz"],
    "Billy Cobham": ["jazz"],
    "Tigran Hamasyan": ["jazz"],
    "Erik Truffaz": ["jazz", "electronic"],
    "Theo Croker": ["jazz", "neo-soul"],
    "Keyon Harrold": ["jazz", "neo-soul"],
    "Takuya Kuroda": ["jazz", "neo-soul"],
    "Nicholas Payton": ["jazz"],
    "Trombone Shorty": ["jazz", "soul-funk"],
    "Butcher Brown": ["jazz", "neo-soul"],
    "Nate Smith": ["jazz", "neo-soul"],
    "Chris Dave": ["jazz", "neo-soul"],
    "Greg Spero": ["jazz", "electronic"],
    "Spirit Fingers": ["jazz"],
    "Mohini Dey": ["jazz", "world"],
    "Miroslav Vitous": ["jazz"],
    "Gonzalo Rubalcaba": ["jazz", "world"],
    "Jacob Collier": ["jazz", "neo-soul"],
    "Jon Cowherd": ["jazz"],
    "John Beasley": ["jazz"],
    "Adam Rogers": ["jazz"],
    "John Ellis": ["jazz"],
    "Sara Caswell": ["jazz"],
    "Gary Campbell": ["jazz"],
    "Gerald Cleaver": ["jazz"],
    "Burniss Travis": ["jazz"],
    "Marcus Gilmore": ["jazz"],
    "Maurice Mobetta Brown": ["jazz", "neo-soul"],
    "Ronnie Foster": ["jazz", "soul-funk"],
    "Bob Baldwin": ["jazz", "soul-funk"],
    "Barney Kessel": ["jazz"],
    "Frank Capp": ["jazz"],
    "Paul Smith": ["jazz"],
    "Filippo Bubbico": ["jazz", "electronic"],
    "Chico Pinheiro": ["jazz", "world"],
    "Yttling Jazz": ["jazz"],
    "Azymuth": ["jazz", "world"],
    "Vandell Andrew": ["jazz", "soul-funk"],
    "Blaque Dynamite": ["jazz", "neo-soul"],
    "Brothers Counsell": ["jazz"],
    "Robert \"Sput\" Searight": ["jazz", "neo-soul"],
    "MonoNeon": ["jazz", "soul-funk"],
    "Louis Cole": ["jazz", "electronic"],
    "Thundercat": ["jazz", "neo-soul"],
    "Flying Lotus": ["electronic", "jazz"],

    # ---- neo-soul / R&B / future-soul ----
    "PJ Morton": ["neo-soul"],
    "Jill Scott": ["neo-soul", "soul-funk"],
    "Bilal": ["neo-soul"],
    "Meshell Ndegeocello": ["neo-soul", "jazz"],
    "Jordan Rakei": ["neo-soul", "uk-jazz"],
    "Jorja Smith": ["neo-soul"],
    "Sampha": ["neo-soul", "electronic"],
    "Cleo Sol": ["neo-soul"],
    "SAULT": ["neo-soul", "soul-funk"],
    "Moonchild": ["neo-soul", "jazz"],
    "Yaya Bey": ["neo-soul"],
    "Yebba": ["neo-soul"],
    "Baby Rose": ["neo-soul"],
    "Charlotte Day Wilson": ["neo-soul"],
    "Madison McFerrin": ["neo-soul"],
    "Aaron Childs": ["neo-soul"],
    "Sasha Keable": ["neo-soul"],
    "Tiana Major9": ["neo-soul"],
    "Yazmin Lacey": ["neo-soul", "uk-jazz"],
    "Celeste": ["neo-soul", "soul-funk"],
    "Selah Sue": ["neo-soul"],
    "Puma Blue": ["neo-soul", "alt"],
    "Elmiene": ["neo-soul"],
    "MorMor": ["neo-soul", "alt"],
    "Arlo Parks": ["neo-soul", "alt"],
    "Greentea Peng": ["neo-soul"],
    "Raheem DeVaughn": ["neo-soul", "soul-funk"],
    "October London": ["neo-soul", "soul-funk"],
    "Rahsaan Patterson": ["neo-soul", "soul-funk"],
    "Arin Ray": ["neo-soul"],
    "Ari Lennox": ["neo-soul"],
    "Blxst": ["neo-soul", "hip-hop"],
    "DESTIN CONRAD": ["neo-soul"],
    "Leon Thomas": ["neo-soul"],
    "Jenevieve": ["neo-soul"],
    "Jimetta Rose": ["neo-soul", "soul-funk"],
    "Georgia Anne Muldrow": ["neo-soul", "jazz"],
    "Zyah Belle": ["neo-soul"],
    "eee gee": ["neo-soul", "alt"],
    "anaiis": ["neo-soul"],
    "DESIREE": ["neo-soul"],
    "MRCY": ["neo-soul"],
    "Nao Yoshioka": ["neo-soul", "soul-funk"],
    "Tanerélle": ["neo-soul"],
    "J. Hoard": ["neo-soul"],
    "Conrad Taylor": ["neo-soul"],
    "Aaron Childs": ["neo-soul"],
    "Kelly Moonstone": ["neo-soul"],
    "Sharada Shashidhar": ["neo-soul", "jazz"],
    "Lubiana": ["neo-soul", "world"],
    "Wesley Joseph": ["neo-soul", "hip-hop"],
    "Mamas Gun": ["neo-soul", "soul-funk"],
    "Soul Speech": ["neo-soul"],
    "Lauryyn": ["neo-soul"],
    "KADEEM.": ["neo-soul"],
    "eniola": ["neo-soul"],
    "Oscar Farrell": ["neo-soul"],
    "Aja Monet": ["neo-soul", "jazz"],
    "aja monet": ["neo-soul", "jazz"],

    # ---- soul / funk / disco classic ----
    "Marvin Gaye": ["soul-funk"],
    "Bobby Womack": ["soul-funk"],
    "Patrice Rushen": ["soul-funk", "jazz"],
    "Raphael Saadiq": ["soul-funk", "neo-soul"],
    "The Jackson 5": ["soul-funk"],
    "Prince": ["soul-funk"],
    "Lisa Fischer": ["soul-funk"],
    "Say She She": ["soul-funk", "neo-soul"],
    "Jalen Ngonda": ["soul-funk"],
    "Omar": ["soul-funk", "neo-soul"],
    "Vikter Duplaix": ["soul-funk", "neo-soul"],
    "Mahalia Jackson": ["soul-funk"],
    "Darrel Walls": ["soul-funk"],
    "Zacardi Cortez": ["soul-funk"],
    "CeeLo Green": ["soul-funk", "hip-hop"],
    "Gnarls Barkley": ["soul-funk", "alt"],
    "Galliano": ["broken-beat", "soul-funk"],
    "Adrian Younge": ["soul-funk", "jazz"],
    "Loren Oden": ["soul-funk"],
    "Ali Shaheed Muhammad": ["hip-hop", "soul-funk"],
    "Charles Stepney": ["soul-funk", "jazz"],
    "Kitty Haywood": ["soul-funk"],

    # ---- hip-hop / rap ----
    "Snoop Dogg": ["hip-hop"],
    "A$AP Rocky": ["hip-hop"],
    "Gucci Mane": ["hip-hop"],
    "Doechii": ["hip-hop"],
    "Freddie Gibbs": ["hip-hop"],
    "billy woods": ["hip-hop"],
    "Black Thought": ["hip-hop"],
    "Goya Gumbani": ["hip-hop", "uk-jazz"],
    "WILLOW": ["alt", "neo-soul"],
    "Guru": ["hip-hop", "jazz"],
    "J. Cole": ["hip-hop"],
    "Mac Miller": ["hip-hop", "neo-soul"],
    "Anderson .Paak": ["neo-soul", "hip-hop"],
    "Common": ["hip-hop", "neo-soul"],
    "Nas": ["hip-hop"],
    "Raekwon": ["hip-hop"],
    "Benny The Butcher": ["hip-hop"],
    "WESTSIDE BOOGIE": ["hip-hop"],
    "D Smoke": ["hip-hop"],
    "50 Cent": ["hip-hop"],
    "Tony Yayo": ["hip-hop"],
    "Havoc": ["hip-hop"],
    "Spice 1": ["hip-hop"],
    "Merkules": ["hip-hop"],
    "KRS-One": ["hip-hop"],
    "Marley Marl": ["hip-hop"],
    "Craig G": ["hip-hop"],
    "Navy Blue": ["hip-hop"],
    "billy woods": ["hip-hop"],
    "Bootie Brown": ["hip-hop"],
    "Dave Jolicoeur": ["hip-hop"],
    "Theophilus London": ["hip-hop", "neo-soul"],
    "Sampa the Great": ["hip-hop", "neo-soul"],
    "Little Simz": ["hip-hop", "uk-jazz"],
    "Dave": ["hip-hop"],
    "Obongjayar": ["neo-soul", "world"],
    "Ty": ["hip-hop"],
    "John Glacier": ["hip-hop", "electronic"],
    "Kwes Darko": ["hip-hop", "electronic"],
    "Kanye West": ["hip-hop"],
    "Ye": ["hip-hop"],
    "Travis Scott": ["hip-hop"],
    "Lil Yachty": ["hip-hop"],
    "Kara Jackson": ["alt", "neo-soul"],
    "Joy Harjo": ["jazz", "world"],
    "J Dilla": ["hip-hop", "neo-soul"],
    "Shafiq Husayn": ["hip-hop", "neo-soul"],
    "Sa-ra Creative Partners": ["neo-soul", "hip-hop"],
    "Om'Mas Keith": ["neo-soul", "hip-hop"],
    "Taz Arnold": ["hip-hop", "neo-soul"],
    "DJ Scratch": ["hip-hop"],
    "WAPO Jije": ["hip-hop", "world"],
    "Frankie hi-nrg mc": ["hip-hop"],
    "Neffa": ["hip-hop"],
    "Gemitaiz": ["hip-hop"],
    "Geolier": ["hip-hop"],
    "Ele A": ["hip-hop"],
    "Chri$tian": ["hip-hop"],
    "thasup": ["hip-hop"],
    "Mara Sattei": ["alt", "hip-hop"],
    "Madame": ["hip-hop"],
    "Marta": ["alt"],
    "Francamente": ["alt", "hip-hop"],

    # ---- electronic (techno / IDM / ambient / bass / downtempo) ----
    "Tom Rowlands": ["electronic"],
    "Modeselektor": ["electronic"],
    "Apparat": ["electronic"],
    "Moderat": ["electronic"],
    "Nathan Fake": ["electronic"],
    "Squarepusher": ["electronic"],
    "Clark": ["electronic"],
    "Four Tet": ["electronic"],
    "Floating Points": ["electronic", "jazz"],
    "Jon Hopkins": ["electronic"],
    "Boards of Canada": ["electronic"],
    "Fred again..": ["electronic"],
    "George FitzGerald": ["electronic"],
    "Matthew Herbert": ["electronic", "jazz"],
    "Nightmares On Wax": ["electronic", "downtempo"],
    "Kruder & Dorfmeister": ["electronic", "downtempo"],
    "Morcheeba": ["electronic", "downtempo"],
    "Tricky": ["electronic", "downtempo"],
    "Beth Gibbons": ["alt", "electronic"],
    "Fink": ["alt", "electronic"],
    "Martyn": ["electronic"],
    "G Jones": ["electronic"],
    "Eprom": ["electronic"],
    "Commodo": ["electronic"],
    "Boys Noize": ["electronic"],
    "Nine Inch Nails": ["alt", "electronic"],
    "Soulwax": ["electronic"],
    "Anz": ["electronic"],
    "Anish Kumar": ["electronic"],
    "salute": ["electronic"],
    "Trance Wax": ["electronic"],
    "Alan Walker": ["electronic"],
    "MJ Cole": ["electronic"],
    "Roni Size": ["electronic"],
    "The Prodigy": ["electronic"],
    "Bizarrap": ["electronic", "hip-hop"],
    "DR. Moriarity": ["electronic"],
    "Godblesscomputers": ["electronic", "downtempo"],
    "S. Fidelity": ["electronic", "hip-hop"],
    "Vegyn": ["electronic"],
    "Yves Tumor": ["alt", "electronic"],
    "Dean Blunt": ["alt", "electronic"],
    "CJ Mirra": ["electronic"],
    "Plumm": ["electronic", "neo-soul"],
    "Dolphin Hyperspace": ["electronic", "jazz"],
    "Hiro Ama": ["electronic", "alt"],
    "Jungle": ["soul-funk", "electronic"],
    "Tom Misch": ["neo-soul", "electronic"],
    "James Blake": ["electronic", "neo-soul"],
    "Bad Snacks": ["electronic"],
    "RIP Magic": ["electronic"],
    "Yes Boone": ["electronic"],
    "mossfellow": ["electronic"],
    "buck": ["electronic"],
    "FourNine": ["electronic"],
    "R3versal": ["electronic"],
    "Hokube": ["electronic"],
    "Renwartherger": ["electronic"],
    "Uècaro": ["electronic"],
    "DJ Gangster": ["electronic", "hip-hop"],
    "Alex Kontsov": ["electronic"],
    "Vuxinatørrsa": ["electronic"],
    "VuxinatørRSA": ["electronic"],
    "DumitrEscu": ["electronic"],
    "King No-One": ["alt"],
    "George FitzGerald": ["electronic"],
    "Polcari": ["electronic"],
    "MUNI": ["electronic"],
    "Siooh": ["electronic"],
    "Mrcl": ["electronic"],
    "azayaka": ["electronic"],
    "PS5": ["electronic"],
    "The Sims": ["electronic"],
    "Lofi Girl": ["electronic", "downtempo"],
    "Boys' Shorts": ["electronic"],
    "Katya Gabeli": ["electronic"],
    "Yukimi": ["electronic", "neo-soul"],
    "Carlos Niño": ["jazz", "electronic"],
    "Carlos Nino": ["jazz", "electronic"],
    "Sup Nasa": ["electronic"],
    "JT": ["electronic"],
    "AINÉ": ["electronic", "neo-soul"],
    "SLWJM": ["electronic"],
    "Arya": ["electronic"],
    "Mandy": ["electronic"],
    "Indiana": ["electronic"],
    "Base Hollow": ["electronic", "neo-soul"],
    "TOMORA": ["electronic", "neo-soul"],
    "Psyché": ["electronic", "neo-soul"],
    "Rudi Creswick": ["electronic", "jazz"],
    "Rssll": ["electronic"],
    "George Osokins": ["classical"],

    # ---- world / afro / latin / indian / global ----
    "Fatoumata Diawara": ["world"],
    "Peter Gabriel": ["world", "alt"],
    "Anoushka Shankar": ["world", "classical"],
    "Shye Ben Tzur": ["world"],
    "The Rajasthan Express": ["world"],
    "Ajay Prasanna": ["world"],
    "Arooj Aftab": ["world", "jazz"],
    "Ibeyi": ["world", "neo-soul"],
    "Yilian Cañizares": ["world", "jazz"],
    "Seu Jorge": ["world"],
    "Roberto Menescal": ["world", "jazz"],
    "Hermanos Gutiérrez": ["world"],
    "Mexican Institute Of Sound": ["world", "electronic"],
    "Meridian Brothers": ["world"],
    "WITCH": ["world", "soul-funk"],
    "Yin Yin": ["world", "electronic"],
    "David Walters": ["world", "neo-soul"],
    "Tambores En Benirras": ["world"],
    "Banda Maje": ["world"],
    "Muca": ["world", "electronic"],
    "Cafe Da Silva": ["world", "jazz"],
    "Rogério Boccato": ["world", "jazz"],
    "Ithamara Koorax": ["jazz", "world"],
    "Gabi Hartmann": ["jazz", "world"],
    "Indra Lesmana": ["jazz", "world"],
    "Masahiro Takahashi": ["electronic", "world"],
    "Tems": ["neo-soul", "world"],
    "Adrian Quesada": ["world", "soul-funk"],
    "Sunshine the Afrooist": ["world", "neo-soul"],
    "Salimata": ["world"],
    "SALIMATA": ["world"],
    "Siân Pottok": ["world", "alt"],
    "M.I.A.": ["electronic", "world"],
    "Kala": ["electronic", "world"],
    "Adrian Sherwood": ["electronic", "world"],
    "Mai Mai Mai": ["electronic", "world"],
    "Pauline Frechette": ["world", "classical"],

    # ---- alt / indie / rock / art-pop / singer-songwriter ----
    "Beck": ["alt"],
    "AURORA": ["alt"],
    "Tame Impala": ["alt", "electronic"],
    "Gorillaz": ["alt", "electronic"],
    "Damon Albarn": ["alt"],
    "Flea": ["alt"],
    "Red Hot Chili Peppers": ["alt"],
    "Foo Fighters": ["alt"],
    "Sigur Rós": ["alt"],
    "Björk": ["alt", "electronic"],
    "David Bowie": ["alt"],
    "Thom Yorke": ["alt", "electronic"],
    "Jonny Greenwood": ["alt", "classical"],
    "Ed O'Brien": ["alt"],
    "Pink Floyd": ["alt"],
    "Arcade Fire": ["alt"],
    "Nick Cave": ["alt"],
    "Aldous Harding": ["alt"],
    "Grian Chatten": ["alt"],
    "Sleaford Mods": ["alt", "electronic"],
    "Jamie T": ["alt"],
    "Jack Johnson": ["alt"],
    "Jack Nitzsche": ["classical", "soul-funk"],
    "Alabama Shakes": ["alt", "soul-funk"],
    "Korn": ["alt"],
    "Primus": ["alt"],
    "Les Claypool": ["alt"],
    "Sean Ono Lennon": ["alt"],
    "The Claypool Lennon Delirium": ["alt"],
    "Joe Satriani": ["alt"],
    "Steve Vai": ["alt"],
    "Art School Girlfriend": ["alt", "electronic"],
    "Saya Gray": ["alt", "neo-soul"],
    "Saya Gray": ["alt"],
    "Archive": ["alt", "electronic"],
    "Emile & The Education": ["alt", "soul-funk"],
    "The Gallands": ["alt", "jazz"],
    "Stéphane Galland": ["jazz"],
    "Elvin Galland": ["jazz"],
    "Sacred Animals": ["alt", "electronic"],
    "Joseph Shabason": ["jazz", "alt"],
    "Gregory Uhlmann": ["alt", "jazz"],
    "Blake Mills": ["alt", "jazz"],
    "Pino Palladino": ["jazz", "neo-soul"],
    "Tom McFarland": ["soul-funk", "electronic"],
    "ROSALÍA": ["alt", "world"],
    "Lady Gaga": ["alt"],
    "Billie Eilish": ["alt"],
    "SZA": ["neo-soul"],
    "Frank Ocean": ["neo-soul", "alt"],
    "Erykah Badu": ["neo-soul"],
    "Ms. Lauryn Hill": ["neo-soul", "hip-hop"],
    "Fugees": ["hip-hop", "neo-soul"],
    "Wyclef Jean": ["hip-hop"],
    "Pras": ["hip-hop"],
    "Bruno Mars": ["soul-funk", "neo-soul"],
    "G-DRAGON": ["alt", "hip-hop"],
    "JENNIE": ["alt"],
    "Sia": ["alt"],
    "JT": ["alt"],
    "Saya Gray": ["alt"],
    "MERVE": ["alt", "electronic"],
    "Coca Puma": ["alt", "electronic"],
    "Camper": ["alt"],
    "Keenyn Omari": ["jazz", "neo-soul"],
    "LIFEOFTHOM": ["neo-soul", "alt"],
    "HAWA": ["alt", "hip-hop"],
    "DJ Harrison": ["neo-soul", "jazz"],
    "Tom Misch": ["neo-soul", "electronic"],
    "Arooj Aftab": ["world", "jazz"],

    # ---- classical / soundtrack / orchestral ----
    "Philip Glass": ["classical"],
    "Ryuichi Sakamoto": ["classical", "electronic"],
    "Sofiane Pamart": ["classical"],
    "Kronos Quartet": ["classical"],
    "Daniel Barenboim": ["classical"],
    "Anton Batagov": ["classical"],
    "Stacy Garrop": ["classical"],
    "Cliff Colnot": ["classical"],
    "Cliff Colnot Orchestra": ["classical"],
    "San Francisco Ballet Orchestra": ["classical"],
    "Georgijs Osokins": ["classical"],
    "Piero Umiliani": ["jazz", "classical"],
    "Piero Piccioni": ["jazz", "classical"],
    "Calibro 35": ["jazz", "soul-funk"],
    "Mexican Institute Of Sound": ["world", "electronic"],
    "The Mariachi Brass": ["world"],
    "Nico Arezzo": ["classical"],
    "Leif Kaner-Lidström": ["classical", "jazz"],
    "Magnus Mehta": ["world", "jazz"],

    # ---- italian heritage / nu-jazz / library ----
    "Nicola Arigliano": ["jazz"],
    "James Senese": ["jazz", "world"],
    "Napoli Centrale": ["jazz", "world"],
    "Raiz": ["world"],
    "LIBERATO": ["alt", "electronic"],
    "Marco Castello": ["alt", "jazz"],
    "Adriano Viterbini": ["alt"],
    "Marcello Giannini": ["alt", "jazz"],
    "Franco Giacoia": ["jazz"],
    "Fabio Di Bartolomeo": ["jazz"],
    "Vittorio de Angelis": ["jazz"],
    "Gaia Banfi": ["alt", "jazz"],
    "Miryam Belfiore": ["jazz", "neo-soul"],
    "Desy": ["neo-soul"],
    "Jason Piccioni": ["jazz"],
    "Polcari": ["electronic"],
    "GINORI 1735": ["electronic"],
    "Alessio Bertallot": ["electronic", "downtempo"],

    # ---- bridge / featured (jazz-soul session circuit) ----
    "Brian Jackson": ["jazz", "soul-funk"],
    "Asha Puthli": ["jazz", "soul-funk"],
    "Duval Timothy": ["jazz", "electronic"],
    "The Pocket Queen": ["jazz", "neo-soul"],
    "Alex Acuña": ["jazz", "world"],
    "Erik Truffaz": ["jazz", "electronic"],
    "Nubiyan Twist": ["uk-jazz", "world"],
    "Kaelin Ellis": ["neo-soul", "electronic"],
    "Steve Lyman": ["jazz"],
    "Michael King": ["neo-soul", "jazz"],
    "Corbin Jones": ["jazz"],
    "Gregory Webster": ["soul-funk"],
    "Mic Holden": ["hip-hop"],
    "Brandon Cordoba": ["jazz"],
    "Miguel Atwood-Ferguson": ["jazz", "classical"],
    "Cary Brown": ["jazz", "neo-soul"],
    "Clyde Cyrus": ["soul-funk"],
    "Yaahn Hunter Jr.": ["neo-soul"],
    "The Colleagues": ["neo-soul"],
    "Private Joy": ["neo-soul"],
    "Amy Gadiaga": ["uk-jazz", "neo-soul"],
    "Barrell Jones": ["uk-jazz"],
    "Samuel Fox": ["neo-soul", "alt"],
    "MC Igu": ["hip-hop", "world"],
    "Che Cax": ["hip-hop"],
    "Shaone": ["hip-hop", "uk-jazz"],
    "Ill Millz": ["hip-hop"],
    "Classix The Writer": ["hip-hop"],
    "Rojo LaVoe": ["hip-hop", "world"],
    "Peter Vogelaar": ["electronic"],
    "Zekkereya El-Magharbel": ["uk-jazz"],
    "Rane Moore": ["classical"],
    "Andy James": ["jazz", "neo-soul"],
    "_BY.ALEXANDER": ["neo-soul"],
    "Dawn Richard": ["neo-soul", "electronic"],
    "Tom Rowlands": ["electronic"],
    "Nesta": ["neo-soul"],
    "NESTA": ["neo-soul"],
    "Starker": ["hip-hop"],
    "YL": ["hip-hop"],
    "FourNine": ["electronic"],
    "Indra Lesmana": ["jazz", "world"],
    "Sup Nasa": ["electronic"],
    "Soul Speech": ["neo-soul"],
    "Marlon Lopez": ["jazz"],
    "DJ Gangster": ["electronic"],
    "Lady Skatina": ["soulful-house"],
    "FORAGER": ["electronic", "neo-soul"],
    "Puma Blue": ["neo-soul", "alt"],
    "Charles Webster": ["soulful-house"],

    "Unknown": ["unknown"],
}

# ---- residual artists completed (domain knowledge + context inference) ----
GENRES.update({
    "Buju Banton": ["world"],            # reggae/dancehall -> world bucket
    "Danger Mouse": ["hip-hop", "alt"],  # producer, Gnarls/Broken Bells
    "Momoko Gill": ["neo-soul", "uk-jazz"],  # UK soul vocalist, broken-beat circuit
    "Melanie Charles": ["jazz", "neo-soul"], # jazz vocalist
    "Salaam Remi": ["neo-soul", "hip-hop"],  # producer
    "Fredrika Stahl": ["jazz", "alt"],       # jazz-pop
    "COLORS": ["neo-soul", "uk-jazz"],       # platform; collaborators skew soul/uk-jazz
    "War Child Records": ["alt", "uk-jazz"], # charity comp; broad alt/jazz roster
    "Angine de Poitrine": ["alt"],           # solo, French alt
    "Esteban Sehinkman": ["soulful-house", "jazz"],  # w/ Charles Webster
    "RamonPang": ["electronic"],             # w/ Four Tet
    "SWEATA": ["neo-soul", "electronic"],    # w/ Kaelin Ellis, Madison McFerrin
})


# =====================================================================
#  API pubblica del modulo — usata da enrich_genres.py
# =====================================================================

# Tassonomia ufficiale (l'ordine definisce anche la priorità di tie-break).
TAXONOMY = [
    "soulful-house", "broken-beat", "uk-jazz", "jazz", "neo-soul",
    "soul-funk", "hip-hop", "electronic", "downtempo", "world",
    "alt", "classical", "unknown",
]

# Lookup case-insensitive costruito una sola volta.
_GENRES_CI = {k.lower(): v for k, v in GENRES.items()}


def artist_genres(artist: str):
    """Restituisce la lista di generi di un artista, o ['unknown'] se assente."""
    return GENRES.get(artist) or _GENRES_CI.get(artist.lower()) or ["unknown"]


def is_known(artist: str) -> bool:
    """True se l'artista è presente in mappa (match esatto o case-insensitive)."""
    return artist in GENRES or artist.lower() in _GENRES_CI


def track_genres(artists, collaborators_lookup=None):
    """
    Inferisce (genres, genre_primary) per un brano a partire dai suoi artisti.

    Pesi: genere primario di ciascun artista = 3, secondario = 2, terziario = 1.
    Il primario del brano è il genere col peso totale più alto; in caso di
    parità si usa l'ordine di TAXONOMY come tie-break deterministico.

    Se un artista è 'unknown' e viene passato `collaborators_lookup`
    (dict artista->generi noti tra i co-autori della stessa traccia), il genere
    viene inferito da quel contesto invece di restare 'unknown'.
    """
    from collections import Counter
    weight = Counter()
    for a in artists:
        glist = artist_genres(a)
        if glist == ["unknown"] and collaborators_lookup:
            # inferenza da contesto: usa i generi noti dei co-autori
            ctx = collaborators_lookup.get(a)
            if ctx:
                glist = ctx
        for i, g in enumerate(glist):
            weight[g] += (3 - i) if i < 3 else 1

    if not weight:
        return ["unknown"], "unknown"

    genres = [g for g, _ in weight.most_common()]
    best = sorted(
        weight.items(),
        key=lambda kv: (-kv[1], TAXONOMY.index(kv[0]) if kv[0] in TAXONOMY else 99),
    )
    return genres, best[0][0]


def coverage(artists):
    """Data una collezione di artisti, ritorna (noti, mancanti)."""
    known = [a for a in artists if is_known(a)]
    missing = sorted({a for a in artists if not is_known(a)})
    return known, missing


def add_artists(mapping: dict):
    """
    Aggiunge/aggiorna artisti a runtime (es. da overrides esterni).
    Aggiorna anche il lookup case-insensitive.
    """
    GENRES.update(mapping)
    for k, v in mapping.items():
        _GENRES_CI[k.lower()] = v
